sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10
matrix:
  include:
    - node_js: "11.0"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    # Allow the nightly installs to fail
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
script: "npm run test"
after_script:
  - "npm i codecov"
  - "./node_modules/.bin/codecov"
